import type { Chapter, Concept, Module } from "../types";
import { glossaryDefinition } from "../data/glossary/abbreviations";

const C = (id:string,title:string,simple:string,formal:string,page:string,terms:string[],example:string,diagramId:string):Concept => ({id,title,simple,formal,sourcePage:page,terms,example,diagramId});
const M = (id:string,chapter:number,title:string,eyebrow:string,minutes:number,concepts:Concept[]):Module => ({id,chapter,title,eyebrow,minutes,concepts,objectives:[`Explain ${title.toLowerCase()} using the lecture terminology`,`Recognise the components, choices and operational trade-offs`,`Apply the chapter recommendations to a realistic IT scenario`]});

export const chapters: Chapter[] = [
  {id:"ch5",number:5,title:"Infrastructure",short:"Networks, datacentres and lifecycle operations",color:"#1e63d5",modules:[
    M("ch5-m1",5,"Network foundations","ARCHITECTURE + ACCESS",42,[
      C("c5-architecture","Network architecture","Network architecture is the design of office, datacentre and wide-area networks that form the foundation of a site's infrastructure.","This chapter is about the design of office networks (wired and wireless), datacentre networks, and the wide area networks (WANs) that connect them. A site's network is the foundation of its infrastructure.","pp. 4-5",["network architecture","site network","LAN","WAN"],"A company documents how office access switches, datacentre cores and branch WAN links work as one design.","d5-architecture"),
      C("c5-physical-logical","Physical versus logical networks","The physical network is the equipment and wiring; the logical network is the software-based segmentation placed over it.","A physical network consists of the physical wires and devices that make up the network. A logical network describes the software-based partitions, segments, and connections that we overlay on the physical network.","p. 6",["physical network","logical network","segment","partition"],"The same switch and cabling can carry separate staff and guest VLANs.","d5-physical-logical"),
      C("c5-vlan","VLAN segmentation","VLANs carve one physical switching infrastructure into manageable logical LAN segments and segregate traffic by switch port.","We build a single physical infrastructure and carve out the individual LAN segments as VLANs. VLANs enable a switch to segregate traffic based on which port it arrived on.","p. 6",["VLAN","LAN segment","traffic segregation","switch port"],"Finance ports are assigned to one VLAN while laboratory ports use another.","d5-vlan"),
      C("c5-osi","OSI model","The OSI reference model divides network communication into logical layers, helping administrators locate and discuss faults consistently.","Open Systems Interconnection (OSI) is a reference model for networks; it looks at the network as logical layers.","p. 7",["OSI","reference model","logical layer","protocol"],"A cable fault is investigated at the physical layer before IP routing is examined.","d5-osi"),
      C("c5-wired","Wired office networks","Wired links trade mobility for a reliable, interference-free physical connection with strong speed and latency characteristics.","Wired connections are more reliable because they are a physical connection, with no radio interference as with Wi-Fi. They are also faster, but lack mobility.","p. 8",["wired network","radio interference","bandwidth","latency"],"VoIP, streaming video and conferencing endpoints benefit from stable wired connections.","d5-wired-wireless"),
      C("c5-wired-path","Jack, IDF and MDF path","A desk device connects through a network jack and building cabling to an IDF patch panel and switch; larger sites connect IDFs back to an MDF.","A person plugs a device into a network jack at a desk. The jack runs through walls and ceilings to a wiring closet or intermediate distribution frame (IDF), where it is patched to a switch port. In large buildings, IDFs connect back to a main distribution frame (MDF).","p. 9",["network jack","patch cable","IDF","MDF"],"Desk jack 2A-17 terminates on an IDF panel, is patched to an access switch, and uplinks to the MDF.","d5-wired-path")
    ]),
    M("ch5-m2",5,"Office network design","SUBNETS + WIRELESS",44,[
      C("c5-subnet-strategies","Office subnet strategies","Office LANs can use one large subnet or divide devices by floor plan, security, change-control needs or function.","The primary strategies for dividing an office LAN into subnets are based on floor plan, security level, change control level, or device function. One big subnet works well for a small office.","p. 10",["subnet","floor plan","security level","device function"],"IoT devices are placed on a different subnet from workstations and servers.","d5-subnet"),
      C("c5-nac","Network access control","NAC authenticates a connecting device or user and decides whether it may join the network and which VLAN it belongs to.","Network access control (NAC) determines whether a device that connects to your network is permitted to join, and which VLAN it should be in. NAC options include MAC-based, authentication-based, and certificate-based checks.","p. 11",["NAC","MAC-based NAC","credentials","certificate"],"A company laptop presents a certificate and is assigned to the managed-device VLAN.","d5-nac"),
      C("c5-wireless-physical","Wireless physical design","Enterprise Wi-Fi must provide sufficient coverage and bandwidth for a larger population and more interference than a home network.","The most important aspects of a wireless network are that it has good coverage and sufficient bandwidth. Do not install a home Wi-Fi base station; use an enterprise-class access point.","p. 12",["Wi-Fi","coverage","bandwidth","enterprise access point"],"A survey identifies coverage gaps before access points are positioned across an office floor.","d5-wireless"),
      C("c5-wireless-logical","Wireless logical design","Wireless NAC can separate company-owned, employee-owned and guest devices into distinct VLANs while keeping a unified SSID strategy.","NAC will put devices into different VLANs based on device type and authentication. Wireless access should be unified across the company, using the same SSID in all branches.","p. 13",["SSID","BYOD","guest network","wireless VLAN"],"The same corporate SSID works at every branch, while identity determines the assigned VLAN.","d5-wireless-logical"),
      C("c5-guest-wifi","Guest wireless security","Guest Wi-Fi is useful, but should still require authentication to prevent outsiders from abusing company infrastructure.","Some authentication should still be required for guest Wi-Fi so that people cannot sit outside the office and use company infrastructure to launch attacks against other sites.","p. 13",["guest Wi-Fi","authentication","abuse prevention"],"Reception issues a time-limited guest credential rather than exposing an open network.","d5-guest")
    ]),
    M("ch5-m3",5,"Datacentre & WAN networks","CORE + CONNECTIVITY",55,[
      C("c5-dc-requirements","Datacentre network requirements","Datacentres have higher machine density and bandwidth demand than offices and organise equipment in racks rather than desk jacks and IDFs.","The LAN in a datacentre has different requirements than the LAN in an office. The datacentre has a higher density of machines and higher bandwidth demands.","p. 14",["datacentre LAN","rack","density","bandwidth"],"A server rack needs multiple high-speed links rather than one office wall jack.","d5-dc"),
      C("c5-central-switch","Central switch with patch panels","In a central-switch design, rack equipment reaches one core through local patch panels; it is simple conceptually but consumes space and cabling.","The datacentre has a single core switch, and each machine connects to it. Patch panels make this manageable, but take valuable datacentre space and involve a lot of cabling.","pp. 15-16",["central switch","patch panel","core switch"],"Every server cable is extended from its rack patch panel to a central network rack.","d5-central-switch"),
      C("c5-tor","Top-of-rack switching","Each rack can have a TOR switch with high-speed core uplinks; paired TORs improve resilience but increase switch count and uplink constraints.","Each rack has its own top-of-rack (TOR) switch. To improve resiliency each rack has two TOR switches and each machine has one connection to each TOR. Bandwidth out of the rack is limited by the switch uplink.","pp. 17-18",["TOR","uplink","dual-homing","resiliency"],"A server connects to TOR-A and TOR-B so one switch can fail without isolating the host.","d5-tor"),
      C("c5-fabric","Datacentre fabric","A unified fabric makes TORs extensions of the core, while a Clos topology provides multiple scalable paths between rack pods.","In a unified fabric product, each TOR is an extension of the core switch. Clos fabrics permit groups, or pods, of racks to have almost infinitely scalable bandwidth by providing multiple paths between any two points.","pp. 19-20",["unified fabric","Clos topology","pod","multiple paths"],"Configuration is performed on the fabric core instead of logging in to every TOR.","d5-fabric"),
      C("c5-dc-logical","Datacentre logical separation","Datacentre subnets remain separate from office subnets and are allocated by security zone and interface function; strong zones may require physical separation.","A datacentre subnet should never be configured outside the datacentre. Subnets for different security zones should be on separate physical devices rather than different VLANs on the same device.","p. 21",["security zone","datacentre subnet","physical separation"],"Public-facing and sensitive backend zones use separate firewall and switching equipment.","d5-dc-zones"),
      C("c5-wan-topology","WAN topologies","WAN strategy combines topology, technology and redundancy; common layouts are star, dual-star, multi-star, ring and provider cloud.","Offices and datacentres are connected via a WAN. Common topologies include star, multi-star, ring, and cloud. A dual-star adds a backup datacentre to improve resilience.","pp. 22-25",["star topology","dual-star","multi-star","ring","cloud topology"],"Regional offices connect to two regional hubs rather than relying on one central datacentre.","d5-wan-topology"),
      C("c5-wan-technology","Dedicated lines, VPN and hybrid WAN","Dedicated lines offer contracted bandwidth and latency at higher distance-based cost; Internet VPNs cost less but vary; hybrid designs combine them for redundancy.","Dedicated lines provide guaranteed bandwidth and latency. VPNs are typically more cost-effective, but bandwidth and latency are not guaranteed. A hybrid approach can use a dedicated line and a VPN for redundancy.","p. 26",["dedicated line","VPN","hybrid WAN","guaranteed latency"],"A branch uses a leased circuit normally and an Internet VPN during circuit failure.","d5-wan-tech"),
      C("c5-routing","Routing strategies","Traffic between subnets can use static routes, interior routing protocols or exterior gateway protocols depending on scale and organisational boundaries.","There are three primary strategies used to route traffic: static configurations, routing protocols, and exterior gateway protocols. Static routing is useful only for a small site.","pp. 27-28",["static route","OSPF","EIGRP","EBGP","routing table"],"OSPF withdraws a failed subnet automatically, while static routes would need manual correction.","d5-routing")
    ]),
    M("ch5-m4",5,"Internet, IPv6 & operations","RESILIENCE + CONTROL",52,[
      C("c5-internet","Internet access architecture","Internet design chooses central, regional or per-site connections and separately considers outbound user access and inbound published services.","There are two aspects to Internet connectivity: outbound access, how people access Internet services, and inbound access, how the company makes services available on the Internet.","pp. 29-30",["outbound access","inbound access","regional hub","single point of failure"],"Regional Internet exits balance user experience, security control and resilience.","d5-internet"),
      C("c5-spof","Internet single point of failure","A single Internet exit is easier to monitor but can disconnect the entire company; multiple controlled exits improve resilience and experience.","Limiting exposure to a single site makes threats easier to monitor, but this one location is a single point of failure. Multiple Internet connections, usually one per regional hub, improve the end-user experience.","p. 30",["single point of failure","Internet exit","redundancy"],"Two regional exits keep other offices online when one hub loses connectivity.","d5-spof"),
      C("c5-sdn","Software-defined networking","SDN makes traffic control programmable: applications state requirements and a controller configures devices to provide an appropriate path.","An SDN enables applications to specify needs such as low latency or bandwidth to a network controller, which dynamically configures network devices to create a specific path.","p. 31",["SDN","network controller","programmable network","traffic path"],"A video service requests a low-latency path from the controller.","d5-sdn"),
      C("c5-ipv6-need","Why IPv6 is needed","IPv6 addresses IPv4 exhaustion and replaces broadcasts with multicast, but it is not upward-compatible with IPv4.","IPv4 has about 3.7 billion usable addresses and the Internet ran out of addresses to allocate in 2015. IPv6 replaces broadcasts with multicast and is not upward compatible with IPv4.","p. 32",["IPv4 exhaustion","IPv6","multicast","compatibility"],"A dual-protocol transition is needed because an IPv6-only host cannot assume IPv4 compatibility.","d5-ipv6"),
      C("c5-ipv6-deploy","Gradual IPv6 deployment","IPv6 should roll out from controlled, lower-risk entry points: Internet-facing load balancers, guest/BYOD networks and test labs.","Strategies include starting with the outside and moving inward, starting with less critical networks such as guest Wi-Fi, and using test labs and slow roll-out strategies.","p. 33",["dual stack","pilot network","guest Wi-Fi","controlled rollout"],"Enable IPv6 from the ISP to one load-balanced website before internal expansion.","d5-ipv6-deploy"),
      C("c5-monitoring","Network monitoring","Monitoring provides the visibility required to operate a network and should cover device health, components, resource use, link health, utilisation and errors.","Monitoring provides visibility that facilitates all other operational tasks. Minimal items include device health, internal components, resource utilisation, and WAN/LAN link health, utilisation and error counts.","pp. 34-35",["health check","utilisation","error count","WAN link"],"An alert shows a bonded link member failing before users report degraded performance.","d5-monitor"),
      C("c5-management","Configuration management and audit","Network management controls configuration and firmware through attributable audit trails, central logs, standard templates and configuration history.","Changes to network devices need to generate an audit trail traceable to a person. Logs should be sent to centralized logging. Configurations should be based on standardized templates and tracked with backups or snapshots.","p. 36",["audit trail","configuration template","snapshot","RANCID"],"A configuration collector records who changed a router and preserves the previous text configuration.","d5-management"),
      C("c5-device-lifecycle","Network-device lifecycle and software","Devices pass through stock, assignment, installation, deployment, operation, service, decommission and disposal; firmware releases are lab-tested and rolled out slowly.","The device life cycle stages are in stock, assigned, installed, deploying, operational, servicing, decommissioning, and disposed. New software releases should be intensively tested and deployed first to less critical devices.","pp. 37-38",["device lifecycle","firmware","lab testing","staged deployment"],"A switch firmware update is automated in the lab before a low-risk production pilot.","d5-device-life"),
      C("c5-network-docs","Network documentation and support","Design documents, DNS, CMDB records and labels support troubleshooting; larger organisations use tiered L1-L3 support and visibility tools.","Network documentation has two purposes: troubleshooting and explaining how the network is put together. Main types are network design and implementation, DNS, CMDB, and labels. Larger companies use L1, L2 and L3 support.","pp. 39-42",["CMDB","forward DNS","reverse DNS","L1 support","path visualisation"],"A path tool exposes asymmetric routing while CMDB data identifies the affected device and vendor.","d5-support")
    ]),
    M("ch5-m5",5,"Datacentre operations","FACILITIES + LIFECYCLE",55,[
      C("c5-dc-types","Datacentre facility types","Computing equipment may be housed in a purpose-built datacentre, colocation, computer room, computer closet or telecom/patch room.","A datacentre is purpose-built for computing equipment; a colocation rents space; a computer room is a single office room; a computer closet may hold one rack; a telecom closet cross-connects wiring without active equipment or cooling.","p. 43",["datacentre","colocation","computer room","telecom closet"],"A small branch uses a computer closet while central systems occupy rented colocation space.","d5-dc-types"),
      C("c5-build-rent","Build, rent, outsource or hybrid","Organisations choose among building, colocation, IaaS, SaaS or a hybrid based on scale, cost and operational responsibility.","Building is generally for very large companies; renting colocation suits small or moderate server real estate; IaaS outsources hardware management; SaaS can avoid datacentre space; mixtures are common.","p. 44",["build","colocation","IaaS","SaaS","hybrid"],"A company keeps regulated servers in colocation and uses SaaS for collaboration.","d5-strategy"),
      C("c5-requirements","Business and technical requirements","Datacentre choices must reconcile availability, continuity, budget, change control, regulation and privacy with service, update, security, access, response and capacity needs.","Business requirements include availability, business continuity, budget, change control, regulatory constraints and data privacy. Technical requirements include services, update frequency, security, remote and customer access, responsiveness and capacity.","pp. 45-46",["OpEx","CapEx","business continuity","regulatory constraint","capacity"],"A regulated service selects a provider only after compliance, recovery and remote-access requirements are verified.","d5-requirements"),
      C("c5-capacity","Capacity management","At the macro level, datacentre operation tracks space, racks, power, cooling, wiring, network and console resources in an accurate inventory.","Running a datacentre is about capacity management: making sure there is enough space, power and cooling. Track occupied, reserved and free rack space; UPS and cooling draw; wiring types; and network and console ports.","pp. 47-49",["rack space","UPS","cooling","console port","inventory"],"Capacity reports prevent a server installation from discovering that all rack power or switch ports are already used.","d5-capacity"),
      C("c5-equipment-life","Datacentre equipment lifecycle","Equipment is installed, changed and maintained before controlled decommissioning frees every allocated resource.","The life cycle starts with installation, followed by moves, adds, and changes, maintenance work, and eventual decommissioning. Disposing of a device in inventory should free all resources it uses.","p. 50",["installation","moves adds and changes","maintenance","decommissioning"],"Removing a server releases rack units, power, switch, console and cable inventory entries.","d5-life"),
      C("c5-cabling-labels","Patch cables and labelling","Patch cables interconnect equipment; types should be distinguishable and equipment, racks, ports and both cable ends should be labelled consistently.","All equipment should be labelled on front and back with its full corporate namespace name. Racks should be labelled by row and position. WAN labels should include the far end and vendor link identity.","pp. 51-53",["patch cable","colour code","asset ID","rack location"],"A fibre uplink label identifies both endpoints and the carrier circuit number.","d5-labels"),
      C("c5-console-tools","Console access, tools and spares","Console servers and KVM switches provide remote console access; datacentres also need organised tools, cables, supplies and commonly failing spares.","Console servers and KVM switches make remote console access possible without a keyboard, monitor and mouse on every system. Tools and spares should be organised, inventoried and easy to move or retrieve.","pp. 54-56",["console server","KVM","tool cart","spares"],"A replacement power supply and labelled cable kit are retrieved quickly during a failure.","d5-console")
    ])
  ]},
  {id:"ch6",number:6,title:"Helpdesks & Support",short:"Customer care, incident handling and durable fixes",color:"#7a3ee6",modules:[
    M("ch6-m1",6,"Customer support","PEOPLE + EXPECTATIONS",48,[
      C("c6-helpdesk","Physical and virtual helpdesks","A formal helpdesk provides a defined human support path at a walk-up counter, by phone, email or ticket system.","A helpdesk may be physical (walk-up counter) or virtual (phone or email). Moving from ad hoc support can be uncomfortable, so new procedures must be communicated clearly. Self-help does not replace human interaction.","p. 4",["physical helpdesk","virtual helpdesk","self-help","formal support"],"Users are directed to a shared queue without losing access to a real support person.","d6-helpdesk"),
      C("c6-friendly","Friendly support presence","The support environment and staff should be pleasant, readable, welcoming and good-natured.","A physical helpdesk should be pleasant and welcoming; a web-based helpdesk should use soothing colours and readable fonts. Staff faces and personalities should also be welcoming and friendly.","p. 5",["customer care","welcoming design","support attitude"],"A calm greeting and readable portal reduce stress before diagnosis starts.","d6-friendly"),
      C("c6-culture","Corporate culture","A helpdesk should reflect and evolve toward the dress, communication and working culture of the customers it serves.","Take time to consider the culture and look of the helpdesk compared with the customers served. Try to evolve to a culture that suits those customers.","p. 6",["corporate culture","dress code","service culture"],"Support for a creative studio uses a less formal interaction style than a regulated office.","d6-culture"),
      C("c6-staffing","Staffing by demand","Helpdesk staffing should focus on call volume and completion time rather than a universal customer-to-attendant ratio.","Sizing a helpdesk is difficult and varies by situation. Rather than focus on customer-to-attendant ratios, focus on call volume ratios and time-to-call completion.","p. 7",["call volume","completion time","staff ratio","support tier"],"Historical ticket arrival rates determine shift staffing more accurately than headcount alone.","d6-staffing"),
      C("c6-scope","Scope of support","A written support policy defines what, who, where and when support applies and the expected average completion time.","A written scope-of-support policy should state what is supported, who is supported, where customers are, when support is provided, and how long the average request should take.","p. 8",["scope of support","support hours","service boundary"],"The policy states that personal devices receive connectivity help but not hardware repair.","d6-scope"),
      C("c6-access-help","How to get help","Clear phone, email and ticket instructions prevent direct interruptions and inappropriate after-hours contact.","The scope-of-support document should specify how to get help. Without clear directions, customers contact SAs directly, interrupting them at inappropriate times or at home.","p. 9",["support channel","ticket system","interruption"],"The company wallpaper displays the helpdesk number, email and portal.","d6-access")
    ]),
    M("ch6-m2",6,"Support process & tickets","SCRIPT + ESCALATE + TRACK",52,[
      C("c6-scripts","Support scripts","A service-specific dialogue script captures the right information and directs the operator to resolve or route a request.","Very large helpdesks use scripts as part of training. Every supported service has an associated flow of dialogue to capture information and tell the operator what to do.","p. 10",["support script","dialogue flow","service request"],"A remote-access script gathers device, location and approval details before routing the request.","d6-script"),
      C("c6-identity","Identity verification","Sensitive support actions require callers to prove identity before the change is made.","A password-reset script should, for security reasons, require callers to prove who they are, possibly with a unique piece of personal information, before a password is set.","p. 10",["identity verification","password reset","personal information"],"The analyst follows the approved verification procedure rather than trusting caller ID.","d6-identity"),
      C("c6-escalation","Escalation process","Escalation moves an issue to someone with greater expertise; first-line staff should solve most calls while higher tiers handle harder or specialist work.","First-line operators should handle 80 to 90 percent of calls and escalate the rest to a second tier. Larger organisations may have four or more tiers, including service builders or maintainers.","pp. 11-12",["escalation","first line","second tier","subject-matter expert"],"A complex directory failure moves from the initial operator to the engineer who maintains the service.","d6-escalation"),
      C("c6-emergency","Written emergency definition","A written definition of emergency helps staff apply consistent priority and lets management resolve disputes.","Every company should define what constitutes an emergency. A written policy empowers SAs to push back and lets management set priorities and provide resources.","p. 13",["emergency policy","priority","management escalation"],"A single broken mouse is not treated like an organisation-wide service outage.","d6-priority"),
      C("c6-tracking","Request tracking","Helpdesk software assigns priority, lists top issues, records request history and can collect customer-satisfaction information.","Every helpdesk needs software to manage requests. It should permit ticket priority, help SAs manage time, log request types and requesters, and automate customer-satisfaction data collection.","p. 14",["ticket","priority","request log","customer satisfaction"],"An analyst opens the queue and works the highest-priority assigned incident first.","d6-ticket"),
      C("c6-statistics","Statistical improvement","Long-term support statistics justify budgets, reveal customer and technology trends and predict costs for new services.","Multiyear trends in customer growth, call volume, call types, technologies, services and satisfaction support budgeting and planning. Past data can predict support costs for new technology.","p. 15",["trend analysis","budgeting","call type","support cost"],"Last year's authentication-ticket volume informs staffing for a new login platform.","d6-stats"),
      C("c6-after-hours","After-hours coverage","Continuous coverage may require three shifts or on-call arrangements, and after-hours responders must be compensated.","Customers increasingly ask for 24/7 coverage. A full three-shift staff may be required, and whoever is contacted after hours must be compensated through incentives or time off.","p. 16",["24/7 coverage","on-call","compensation","shift"],"A rotating on-call engineer receives an allowance and recovery time after overnight work.","d6-hours"),
      C("c6-different-desks","Different helpdesks for different needs","Separate groups may receive new-service requests, diagnose service problems and perform physical installations, each with suitable supervision and skills.","It may make sense to have separate helpdesks for new services and problems, with a third group for installations. Groups can have different supervisors and training.","p. 17",["service request","incident desk","installation team"],"One team provisions accounts while another handles failures of existing accounts.","d6-desks")
    ]),
    M("ch6-m3",6,"Incident handling","FOUR PHASES + NINE STEPS",50,[
      C("c6-process","Customer-request process","A structured incident method gathers, evaluates, fixes and verifies trouble tickets, calls and problem reports.","The process defines how customer requests are gathered, evaluated, fixed, and verified. Customer requests include trouble tickets, calls, and problem reports.","p. 18",["incident report","customer request","verification"],"Every request follows the same visible path from first contact to confirmed closure.","d6-process"),
      C("c6-greeting","Phase A: greeting","Step 1 establishes a respectful connection and starts the support interaction.","Phase A is The Greeting ('Hello!'). Step 1 is the greeting.","pp. 19-20",["Phase A","greeting"],"The analyst welcomes the customer and introduces the helpdesk.","d6-incident"),
      C("c6-identification","Phase B: problem identification","Classification, a precise problem statement and verification turn the initial report into a shared, testable understanding.","Phase B asks 'What's wrong?' Step 2 is problem classification, Step 3 is problem statement, and Step 4 is problem verification.","pp. 19-20",["problem classification","problem statement","problem verification"],"The analyst restates the affected service, user scope and expected behaviour, then reproduces it.","d6-incident"),
      C("c6-execution","Phase C: planning and execution","Propose feasible solutions, choose one with the customer or process owner, then execute it carefully.","Phase C is Planning and Execution ('Fix it'). Step 5 is solution proposals, Step 6 is solution selection, and Step 7 is execution.","pp. 19-20",["solution proposal","solution selection","execution"],"Two recovery options are compared before the lower-risk one is applied.","d6-incident"),
      C("c6-verification","Phase D: verification and closing","The practitioner verifies technical correctness, then the customer verifies that the original need is met before closure.","Phase D is Verification ('Verify it'). Step 8 is craft verification and Step 9 is customer verification/closing.","pp. 19-20",["craft verification","customer verification","closing"],"Monitoring is healthy and the customer confirms that email works again before the ticket closes.","d6-incident"),
      C("c6-optimise","Optimising customer care","Training, holistic improvement, customer familiarity, outage announcements, trend analysis and process-aligned architecture improve support.","Optimizing customer care includes model-based training, holistic improvement, increased customer familiarity, special announcements for major outages, trend analysis, customers who know the process, and an architecture that reflects the process.","p. 21",["model-based training","major outage","trend analysis"],"A portal banner diverts duplicate calls during a known outage.","d6-optimise")
    ]),
    M("ch6-m4",6,"Debugging","CAUSE + METHOD + TOOLS",50,[
      C("c6-understand","Understand the customer's goal","Begin with what the customer is trying to accomplish, because their technical diagnosis may be incomplete or outside their expertise.","A customer unable to read email may report a broken program, unreachable server or missing mailbox, while the cause could be network, power or DNS. Gain a high-level understanding of what the customer is trying to do.","p. 22",["customer goal","reported symptom","technical cause"],"Ask 'What were you trying to do?' before accepting 'the server is broken' as the diagnosis.","d6-understand"),
      C("c6-root-cause","Cause rather than symptom","Workarounds and fast recovery may be necessary, but sustainable reliability requires fixing the root cause.","SAs must find and fix the cause, not simply work around the problem. Deleting logs fixes a symptom; rotating and automatically deleting logs fixes the problem.","p. 23",["root cause","symptom","workaround","sustainable reliability"],"Restarting a service restores it now; correcting the resource leak prevents recurrence.","d6-root"),
      C("c6-elimination","Process of elimination","Remove or bypass parts until the fault disappears; the last removed portion contains the problem.","Process of elimination entails removing different parts of the system until the problem disappears. The problem must have existed in the last portion removed.","p. 24",["process of elimination","isolation","hypothesis"],"Bypass the switch, cable and adapter one at a time to isolate a link fault.","d6-elimination"),
      C("c6-refinement","Successive refinement","Build or add components step by step and verify the desired change after each addition.","Successive refinement involves adding components to the system and verifying at each step that the desired change happens.","p. 24",["successive refinement","incremental test"],"Start from a minimal working configuration and add integrations until the failure returns.","d6-refine"),
      C("c6-network-bugs","Six classes of network bugs","Network performance can be limited by loss/corruption/congestion/hardware, routing/latency, reordering, buffers, packet size or inefficient applications.","Six classes can limit network performance: packet losses, corruption, congestion or bad hardware; IP routing or long round trips; packet reordering; inappropriate buffer space; inappropriate packet sizes; and inefficient applications.","p. 25",["packet loss","packet reordering","buffer","round-trip time"],"A saturated buffer can mask an application inefficiency until the first bottleneck is fixed.","d6-bugs"),
      C("c6-training","Training and underlying technology","Formal training offers focused, complete and lab-based learning; deep knowledge of system internals improves debugging.","Formal training removes job interruptions, covers complete features, exposes practical details and provides a lab. Understanding underlying technology and available internal mechanisms makes systems easier to debug.","pp. 26-27",["formal training","lab","system internals"],"An administrator reproduces a fault safely in a training lab before touching production.","d6-training"),
      C("c6-tools","Choose the simplest useful tools","Prefer a tool that solves the immediate problem simply and combines well with other tools rather than unnecessary complexity.","The best tool provides the simplest solution to the problem at hand and can be easily combined with other tools. NFS mounting problems can be debugged with ping, traceroute, and rpcinfo.","p. 28",["ping","traceroute","rpcinfo","tool selection"],"Use a path trace and service query before deploying a large monitoring suite for one fault.","d6-tools")
    ]),
    M("ch6-m5",6,"Durable fixes & documentation","FIX ONCE + SHARE",48,[
      C("c6-temporary","Temporary and permanent fixes","Constraints may require a temporary repair, but it must be recorded and followed by scheduled permanent work.","A quick fix may be required until a maintenance window, software or hardware is available. Manually deleting logs is temporary; installing log rotation is permanent. Record that the issue must be revisited.","pp. 29-30",["temporary fix","permanent fix","maintenance window","technical debt"],"A ticket schedules log rotation after emergency manual cleanup restores disk space.","d6-fix"),
      C("c6-automation","Safe automation","Automation may fix symptoms or root causes, but must act carefully, log its work and alert an administrator when permanent follow-up is needed.","Automation should be extremely careful and keep logs so its work can be audited. If it fixes only symptoms, it is critical that it alert an SA to implement a permanent fix.","p. 31",["automation","audit log","alert","root cause"],"An automated service restart records the event and opens a follow-up incident.","d6-automation"),
      C("c6-what-doc","What to document","Prioritise complicated, unpleasant or frequently explained work; process documents also reveal role responsibilities and required skills.","The most important things to document tend to be complicated and unpleasant or things that you explain all the time. Responsibilities come from documented processes; required skills come from their technologies.","p. 32",["process documentation","responsibility","required skill"],"A recurring offboarding checklist becomes both a runbook and part of the administrator role definition.","d6-docs"),
      C("c6-template","Documentation template","A useful starter document contains a clear title, author and revision metadata, a goal description and actionable steps.","A simple template has: Title; Metadata (author contact and revision history); What (contents or goal); and How (steps to accomplish the goal).","p. 33",["title","metadata","revision history","procedure"],"A password-reset runbook states its owner, last revision, purpose and numbered steps.","d6-template"),
      C("c6-sources","Documentation sources and checklists","Screenshots, command-line capture, email and ticket records provide raw material; checklists standardise repeatable high-risk work.","Easy sources are saving screenshots, capturing the command line, leveraging email, and mining the ticket system. Typical checklists cover hires, terminations, OS installation, archiving and OS security.","pp. 34-35",["screenshot","command capture","checklist","ticket mining"],"A resolved ticket is converted into a tested HOWTO and checklist.","d6-sources"),
      C("c6-wiki","Wiki and findability","A wiki supports accessible collaborative editing and revision history; full-text search and descriptive synonyms make content findable.","A wiki is a web-based documentation repository where authorised users add and edit documents. Search, titles, descriptions, synonyms, technical names, brand names and common names improve findability.","pp. 36-37",["wiki","revision history","full-text search","findability"],"Searching both 'MFA' and 'two-factor login' locates the same support article.","d6-wiki"),
      C("c6-cms","Content-management system","A CMS separates stored content, history controls and presentation, and can publish IT status and outage information.","A CMS has three layers: repository, history, and presentation. The history layer provides version control, permissions, audit trails and global identifiers.","p. 38",["CMS","repository layer","history layer","presentation layer"],"A scheduled maintenance article is approved, versioned and published automatically.","d6-cms"),
      C("c6-doc-uses","Documentation uses","A documentation system may support self-help, internal procedures, HOWTOs, FAQs, reference lists, runbooks, scripts and a technical library.","Additional uses include a self-help desk, group-specific documents, HOWTOs, FAQs, reference lists, procedure/checklist/runbook/script repositories and a technical library.","p. 39",["HOWTO","FAQ","runbook","technical library"],"An FAQ links a short answer to a detailed HOWTO and current service status.","d6-doc-life")
    ])
  ]},
  {id:"ch7",number:7,title:"Change Processes",short:"Safe change, maintenance and centralisation",color:"#d97706",modules:[
    M("ch7-m1",7,"Change governance","PROPOSE + ASSESS + REVIEW",55,[
      C("c7-management","Change management and CRB","Change management coordinates work whose impact ranges from a few users to millions; a CRB defines process, risk standards, approvals and post-change coordination.","A Change Review Board assures that a business can make required changes in a coordinated manner. It defines processes and risk standards, reviews requests, and coordinates post-change activities.","pp. 4-5",["change management","CRB","change request","post-change activity"],"A core-network change is reviewed for conflicts with other company initiatives.","d7-change"),
      C("c7-proposal","Change proposal process","A structured form explains the exact change; early submission and pre-checking let CRB members review efficiently.","People write proposals and the CRB meets weekly to discuss and approve them. Proposals should be submitted early and pre-checked. The form should ask for a detailed explanation of the changes.","p. 6",["change proposal","pre-check","structured form"],"The proposer submits commands, affected systems and owners before the weekly meeting.","d7-proposal"),
      C("c7-classification","Change classifications","CRBs distinguish routine, major, sensitive and emergency updates by expected outage, breadth and urgency.","Routine updates have no expected outage and near-zero unintended-outage chance; major updates affect many systems or require significant outage; sensitive updates expect no outage but are large; emergency updates cannot wait for the next CRB.","p. 7",["routine update","major update","sensitive update","emergency update"],"A critical vulnerability fix receives emergency approval from one CRB member and later full review.","d7-class"),
      C("c7-risk","Risk discovery and quantification","Risk combines failure likelihood with potential impact and determines whether review is low, medium or high.","Change requests should be rated high, medium, or low risk. The rating is based on potential impact and likelihood. High impact with medium or high likelihood is high risk; low impact with low or medium likelihood is low risk.","p. 8",["risk rating","impact","likelihood","severity"],"A high-impact change remains high risk even when likelihood is only medium.","d7-risk"),
      C("c7-plan","Five-part technical plan","A complete plan contains change steps, test evidence, success criteria, a backout plan and a decision point.","The five primary parts are the change process, testing documentation, success criteria, backout plan, and decision point defining how and when to back out.","p. 9",["success criteria","backout plan","decision point","staging"],"If error rate exceeds the defined threshold before the deadline, the team restores the old configuration.","d7-plan"),
      C("c7-schedule-communicate","Scheduling and communication","Major or sensitive changes belong outside peak use or in a planned window, and both IT and customers need clear impact, date and time information.","Sensitive updates should happen outside peak usage. IT and customers must know what is happening; customers need to understand the impact, date and time. Communication methods depend on company culture.","pp. 10-11",["off-peak","maintenance window","change communication"],"A weekend change is announced through the channel employees actually use.","d7-communication"),
      C("c7-tiered","Tiered CRBs and freezes","Large organisations promote higher-risk work through technical, IT-management and business-aware review tiers; freezes prohibit major and sensitive work at critical times.","The lowest CRB checks technical planning and testing; the next includes higher IT managers; the final tier reviews promoted high-risk changes against business needs. Change freezes prohibit sensitive and major updates, for example at fiscal year-end.","p. 12",["tiered CRB","change freeze","high-risk change","fiscal year"],"A payment change reaches the top CRB and is kept outside the festive freeze.","d7-tiered")
    ]),
    M("ch7-m2",7,"Server upgrades","CHECKLIST + BACKOUT",42,[
      C("c7-strategies","Upgrade strategies","A server can be upgraded in place or replaced with a newly built machine followed by client migration.","There are two main strategies: upgrade the host in-place, or build a new machine and migrate clients to it. A paper checklist is the single tool required for success.","p. 13",["in-place upgrade","migration","checklist"],"A new host is built and tested before DNS moves clients from the old server.","d7-upgrade"),
      C("c7-service-checklist","Service and compatibility checklist","First identify services, customers and packages, then verify package compatibility and define a test for every service.","Develop a service checklist: services, customers, and packages. Verify each package works with the new OS or plan an upgrade path. For each service, develop a test.","p. 14",["service checklist","compatibility","service test"],"The team records that DNS, DHCP and monitoring agents must all work on the target OS.","d7-upgrade"),
      C("c7-upgrade-plan","Upgrade planning","Choose the strategy, write implementation and triggered backout plans, select a window, announce it and re-run tests.","Choose an upgrade strategy; write detailed implementation and backout plans with specific triggers; select a maintenance window; announce the upgrade; and execute the tests again to confirm they remain valid.","p. 14",["implementation plan","backout trigger","maintenance window"],"A package incompatibility discovered in the final rehearsal stops the production upgrade.","d7-upgrade"),
      C("c7-upgrade-execute","Upgrade execution and learning","Lock out customers, upgrade with a helper, repeat tests, back out on trigger, restore access, communicate outcome and update the checklist.","Lock out customers; do the upgrade with someone watching; repeat tests; execute backout if triggered; let customers back in; communicate completion or backout; analyse the outcome and modify the checklist.","p. 14",["lockout","mentor","post-change review"],"After success, a missed monitoring step is added to the checklist for next time.","d7-upgrade")
    ]),
    M("ch7-m3",7,"Maintenance windows","PREPARE + EXECUTE + RESOLVE",58,[
      C("c7-window","Maintenance-window purpose","A maintenance window concentrates risky work into a short, customer-coordinated period of lower impact.","A maintenance window is a short period in which a lot of system work is performed. It is often disruptive, so scheduling must be done in cooperation with customers.","p. 15",["maintenance window","planned outage","customer coordination"],"Several dependent upgrades share one approved overnight window.","d7-window"),
      C("c7-stages","Three maintenance stages","Preparation schedules the window, selects a flight director, prepares proposals and builds a master plan; execution disables access, follows shutdown order, performs work and tests; resolution announces completion and restores access.","The three stages are preparation, execution and resolution. Preparation includes scheduling, a flight director, proposals and master plan; execution includes disabling access, shutdown sequence, plan and testing; resolution includes announcement, access and readiness for problems.","p. 16",["preparation","execution","resolution","flight director"],"The flight director tracks every proposal and releases services only after system tests pass.","d7-stages"),
      C("c7-buyin","Management buy-in","Avoid critical business dates and explain windows in terms of company benefit; management must approve outages or reduced capacity.","Avoid month-end, quarter-end, fiscal year-end and relevant product releases. Management must know and sign off, and the concept must be sold as a business benefit.","p. 17",["management buy-in","business calendar","reduced capacity"],"The proposal quantifies risk reduction rather than saying the window is convenient for administrators.","d7-buyin"),
      C("c7-proposals","Maintenance change proposals","All proposals should be submitted about one week before the window so they can be coordinated into the plan.","One week before the maintenance window, all change proposals should have been submitted.","pp. 18-20",["proposal deadline","master plan","SecurID upgrade"],"Late non-emergency work is deferred instead of silently inserted into the window.","d7-proposals"),
      C("c7-disable","Disabling access","The first execution task is to disable or discourage access and remind users through signs, remote-access controls, announcements and helpdesk messages.","The first task is to disable or discourage system access. This may include notices, disabling VPN/dedicated/wireless access, public announcements and a changed helpdesk voicemail message.","p. 21",["remote access","maintenance notice","helpdesk message"],"VPN access is disabled only after the final maintenance reminder.","d7-disable"),
      C("c7-mechanics","Dependencies, console and communication","Test tools first; boot foundational name, authentication, licence, application and data services before dependent compute systems, using KVM, console or LOM and an open communication bridge.","Test console servers and tools before the window. Critical systems such as console, name, authentication, licence, application and data servers typically boot before compute servers and desktops. KVM, serial console and LOM provide remote access.","p. 22",["shutdown sequence","boot sequence","KVM","LOM","conference bridge"],"DNS and authentication become available before user desktops are released.","d7-dependencies"),
      C("c7-testing","Comprehensive testing and reopening","Testing depth should match the breadth of work; teams receive assigned machines and tests, then remote access and helpdesk messages are restored.","After extensive work, plan substantial system testing. The flight director splits the team into groups with assigned machines and tests. The final act is to re-enable remote access and restore helpdesk voicemail.","pp. 23-24",["system testing","test team","re-enable access"],"The exit checklist prevents the team from forgetting to restore VPN access.","d7-testing"),
      C("c7-ha","High-availability maintenance","HA sites keep services available by planning around redundant architecture and monitoring overall availability throughout the work.","HA sites still schedule and communicate, plan beforehand, use a flight director and proposals, test fully and benefit from console access. They require redundancy, do not disable access, and closely monitor the service as a whole.","pp. 24-26",["high availability","redundancy","service monitoring","capacity"],"Traffic drains from one redundant node while it is maintained, then returns before its peer is touched.","d7-ha")
    ]),
    M("ch7-m4",7,"Centralisation models","CENTRAL + DISTRIBUTED",50,[
      C("c7-models","Centralised, decentralised and distributed","Centralised services run from one organisation or platform; decentralised services are independently designed and operated; distributed services deploy one central standard at multiple locations.","A centralized model uses one platform; a decentralized model lets each division design, create and operate its own; a distributed model centrally creates a standard, deploys it in each division, and centrally manages it.","p. 27",["centralized","decentralized","distributed"],"One centrally managed email design is deployed in regional instances.","d7-central"),
      C("c7-central-rationale","Rationale for centralisation","Centralisation reduces duplicated work and cost while improving consistent service quality.","Centralization brings efficiency by reducing duplication of effort. A single team tests, certifies and deploys software rather than repeating the work in every region. It should also improve service quality.","p. 28",["efficiency","duplication","service quality"],"One team certifies an update for all divisions.","d7-rationale"),
      C("c7-decentral-rationale","Rationale for decentralisation","Groups may decentralise because of low quality, unmet needs, limited customisation, perceived cost advantage or desire for faster features.","Motivations include low quality, needs not met, lack of customizability, cost, and desire for new features. End-user satisfaction is often linked to on-site support and fast response.","pp. 28-29",["local support","customizability","unmet need"],"A research team seeks its own platform because the central service cannot support a required feature.","d7-decentral"),
      C("c7-hybrids","Hybrid approaches","Real organisations can use strict centralisation, a subscribed central platform, delegated local support, controlled exceptions or weak 'leaky' exceptions.","Hybrid strategies are strictly centralized service, centralized platform, centralized with decentralized delegation, centralized with well-defined exceptions, and centralized with leaky exceptions.","p. 30",["centralized platform","delegation","exception","leaky exception"],"A central network architecture is operated day-to-day by regional teams.","d7-hybrid")
    ]),
    M("ch7-m5",7,"Recommendations & migration","STANDARDISE + MOVE",60,[
      C("c7-security","Architecture and security centralisation","Unified architecture simplifies support; security policy, authentication and sensitive-data protection benefit from strict central control.","A unified architecture makes the site easier to support. Strictly centralized security avoids inconsistent policies. Central authentication gives users one credential set; centralized authorization lets owners define access policies.","pp. 31-33",["authentication","authorization","extranet","DLP"],"A central identity service supplies credentials while application owners define entitlements.","d7-security"),
      C("c7-infra","Infrastructure recommendations","Datacentre standards, network design/tooling, IP address space and namespaces should be centrally governed, with selected operations delegated regionally.","Centralizing infrastructure ensures compatibility, simplifies documentation and support, reduces costs, fosters automation and improves services. Network design and tooling should be centralized with regional delegation and one central NOC.","pp. 34-35",["NOC","IP address management","namespace management","regional delegation"],"Central address allocation prevents the same subnet being used at two sites.","d7-infra"),
      C("c7-monitor-log","Monitoring and logging platforms","Central monitoring prevents duplicate polling and enables event correlation while subscribers control targets and alerts; central logging needs scalable storage and archives.","A centralized monitoring platform lets subscribers define what and how to monitor, plug-ins, frequency, recipients and severity. Central logging enables correlation and needs dedicated storage with automated archiving and retrieval.","p. 36",["event correlation","monitoring platform","log archive"],"A shared platform correlates several device alarms to one failed WAN link.","d7-monitor"),
      C("c7-support","Support recommendations","Use one central helpdesk and a unified global IT organisation, but balance efficiency with local end-user presence.","All companies should have a single centralized helpdesk. Regional staff should report into a unified global IT organisation. Customer satisfaction is strongly linked to local support, but staff at every small office is expensive.","pp. 37-38",["central helpdesk","local presence","global IT"],"A travelling support schedule gives small offices regular local assistance while one queue coordinates work.","d7-support"),
      C("c7-seven-steps","Seven steps to centralise","Understand the current service, plan, gain support, fix causes of decentralisation, provide a better service, ramp slowly and pursue easy early wins.","The steps are: understand the current solution; make a detailed plan; get management support and budget; fix the problems that led to decentralization; provide an excellent service; start slowly and ramp up; look for low-hanging fruit.","p. 39",["stakeholder","migration plan","management support","low-hanging fruit"],"A tolerant pilot group moves first and validates the new service.","d7-migrate"),
      C("c7-understand-plan","Understand and plan migration","Interview stakeholders about features, strengths, weaknesses, users and change processes, then define the target work, participants, effort and migration.","Understand features, strong and weak points, change processes, users and why the service is decentralized. Then define needed changes and a detailed plan of work, people, time and migration effort.","pp. 40-41",["questionnaire","stakeholder interview","SLA","migration effort"],"A questionnaire reveals that slow change approval—not technology—caused teams to break away.","d7-migrate"),
      C("c7-fix-excel","Fix problems and provide excellence","Correct known issues before migration and make the central service tangibly faster, reliable, full-featured, automated, customisable, cheaper and better supported.","Fix prioritised problem areas, then make the centralized service significantly better in ways users can see: fast, highly reliable, full-featured, automated and customizable.","p. 42",["known issue","service improvement","automation"],"The target meets the missing feature and response-time needs before inviting users.","d7-excellence"),
      C("c7-slow-boundaries","Start slowly and manage boundaries","Begin with failure-tolerant users; if decentralisation remains, define strong technical and security boundaries so one service cannot damage another.","Start with users most tolerant of failures and fix early bugs. For decentralized services, define clear boundaries and interfaces using existing technologies and protocols so problems cannot propagate.","pp. 43-44",["pilot","service boundary","interface","isolation"],"Independent identity systems use a documented protocol boundary instead of sharing an unmanaged database.","d7-boundary")
    ])
  ]},
  {id:"ch8",number:8,title:"Service Recommendations",short:"Monitoring, naming and dependable services",color:"#07866d",modules:[
    M("ch8-m1",8,"Monitoring & namespaces","OBSERVE + NAME",55,[
      C("c8-monitor","Real-time and historical monitoring","Monitoring observes system state for decisions; real-time alerts prompt immediate response while historical records support capacity and anomaly detection.","Monitoring is the primary way we gain visibility. Real-time alerts report interfaces, load and security events. Historical trends record usage for capacity planning and detect behavioural abnormalities before problems.","p. 4",["real-time alert","historical trend","capacity planning","anomaly"],"A link-down alarm pages support while a 90-day graph supports an upgrade request.","d8-monitor"),
      C("c8-pitfalls","Monitoring system concerns","A complete platform must handle historical collection, real-time detection, prioritisation, alert cascades, coordination, centralisation and advanced tests.","Pitfalls include gathering, storing and viewing historical data; real-time detection and alerting; scaling through prioritisation, cascading alerts and coordination; centralisation; and advanced end-to-end, response-time, compliance and meta-monitoring.","p. 5",["cascading alert","end-to-end test","response time","meta-monitoring"],"One dependency failure is grouped instead of paging teams for every downstream symptom.","d8-monitor-flow"),
      C("c8-namespace","Namespace basics","A namespace is a set of unique keys with attributes and needs policy, procedures and central management.","A namespace consists of a set of unique keys and attributes associated with each key. It needs policies for naming, longevity, locality and exposure; procedures for adding, changing and deleting; and centralized management.","p. 6",["namespace","unique key","attribute","central management"],"Employee IDs are unique keys with department and status attributes.","d8-namespace"),
      C("c8-name-types","Ways to define names","Names may be functional, descriptive, formula-based, themed, unstandardised or hybrid.","Functional names express roles; descriptive names communicate facts; formula-based names follow a strict formula; a theme groups names; other choices are no standard and hybrid.","p. 7",["functional name","descriptive name","formula-based name","theme"],"A printer name encodes building, floor and print type.","d8-name-types"),
      C("c8-lifetime","Name lifetime and reuse","Policy decides when unused names are removed and whether they are reused immediately, after a delay or not at all.","Names may be removed immediately or after a set time. Functional names may be reused immediately; usernames and email addresses may be reused only after a set time.","p. 8",["name lifetime","name reuse","functional name"],"A departed employee's email address is held to prevent misdirected mail.","d8-lifetime"),
      C("c8-usage","Namespace usage and authority","One namespace may span many services, so scope, attribute consistency and the authoritative source must be defined.","A login ID namespace may be used in HR, accounts, authentication, authorization and email. Consider scope, when attributes stay consistent, and which service is authoritative.","p. 9",["scope","consistency","authoritative source"],"HR is authoritative for employment status and drives access removal.","d8-usage")
    ]),
    M("ch8-m2",8,"Name-service reliability","DNS + DHCP + LDAP + AAA",62,[
      C("c8-data","Name-service data design","For every name service, define stored data, namespaces, consistency, authority, access methods, scaling limits and capacity.","Ask which data and namespaces are stored, consistency requirements and mechanisms, authoritative service, access methods and their scaling limits, and data capacity limit.","p. 10",["name service","consistency requirement","access method","capacity limit"],"A directory design records which database owns employee department data.","d8-nameservice"),
      C("c8-reliability","Name-service reliability","Name services must be highly reliable because many dependent services can fail in a cascade when naming fails.","The first and most important consideration is high reliability. Many other services rely on name services, so failure can cause widespread cascading failures.","p. 11",["cascading failure","high reliability","dependency"],"Email, login and web access all appear broken when DNS is unavailable.","d8-dependencies"),
      C("c8-dns-resolver","DNS resolvers and anycast","Clients use one or more resolvers; multiple resolvers and an anycast address improve resilience and route clients to an appropriate server with faster failover.","Clients are configured with one or more DNS resolvers. Anycast looks like unicast, but routers send packets to a server advertising that address using routing metrics, making server IPs independent of client configuration and speeding failover.","pp. 12-14",["DNS resolver","anycast","routing metric","failover"],"The same resolver address reaches a nearby regional server and automatically shifts when it fails.","d8-anycast"),
      C("c8-authoritative","Authoritative DNS architecture","Resolvers use root servers; each DNS zone should have multiple authoritative servers, with master/slave or multi-master update architecture.","Authoritative servers contain zone data, and a zone should be served by multiple servers. In master/slave, slaves continue serving if the master fails, but dynamic updates stop; multi-master is another option.","pp. 15-16",["authoritative DNS","root server","master/slave","multi-master","zone"],"Two slaves answer existing records while the failed master is repaired.","d8-dns"),
      C("c8-dhcp","DHCP failover","DHCP servers should run in pairs because changing server definitions across every subnet after failure is not trivial.","DHCP is another name service. Always set up servers in pairs and use failover; because DHCP servers are defined on every subnet, switching after a failure is not trivial.","p. 17",["DHCP","failover pair","subnet"],"The partner DHCP server continues leases when one node is down.","d8-dhcp"),
      C("c8-ldap","LDAP and Active Directory","LDAP supports distributed directories; resilience may use a load-balanced master architecture, while Active Directory uses multi-master domain controllers.","LDAP commonly provides directories for authentication, contact data and systems. A resilient service can place the master behind a load balancer. Active Directory is LDAP-based in a multi-master setup and can feed integrated DNS.","p. 18",["LDAP","Active Directory","domain controller","load balancer"],"Multiple domain controllers accept directory updates and provide integrated DNS.","d8-ldap"),
      C("c8-aaa","Authentication, authorization and accounting","AAA services use protocols such as RADIUS and TACACS+ and consult identity and authorization sources for applications and network services.","AAA is a core name service. RADIUS and TACACS+ are common protocols. AAA servers refer to external name services to verify identity and obtain authorization parameters.","pp. 19-20",["AAA","RADIUS","TACACS+","authentication","authorization"],"A network login is verified against Active Directory and permissions come from an authorization database.","d8-aaa"),
      C("c8-database","Databases as name services","HR, CMDB and authorisation databases can be master sources whose changes automatically update dependent directories and systems.","Databases such as HR, CMDB and centralized authorization provide name services and often drive other systems. Marking a person as no longer employed should change authentication, email, contact and authorization directories.","p. 21",["HR database","CMDB","master database","provisioning"],"An HR termination event automatically disables authentication and email.","d8-database")
    ]),
    M("ch8-m3",8,"Email & print services","COMMUNICATE + OUTPUT",56,[
      C("c8-email-policy","Email privacy and retention policy","Email policy defines personal versus commercial use, monitoring and authorised reading, plus legally informed retention.","A personal-use policy states when employee email may be read, by whom and under what circumstances, including automatic monitoring. Retention policy reflects legal requirements.","p. 22",["privacy policy","personal use","retention policy","monitoring"],"The policy identifies the legal approval required before mailbox access.","d8-email-policy"),
      C("c8-email-namespace","Email namespace","Create a unique organisation-wide address namespace and use a directory, because first.last formats inevitably collide.","Avoid first.last addresses because duplicates occur. Create a unique organization-wide namespace and use a directory to look up addresses.","p. 23",["email namespace","address collision","directory"],"Two employees named John Smith receive stable unique IDs with friendly directory lookup.","d8-email-name"),
      C("c8-email-reliability","Email reliability","Users expect email to behave like power; use redundant servers, backup MX, RAID and redundant interfaces, power supplies and processors.","Customers expect the same reliability as power, and failures generate many calls. Measures include redundant servers, backup MX hosts, RAID arrays, and multiple NICs, power supplies and processors.","p. 24",["backup MX","RAID","redundant server","NIC"],"A backup MX accepts inbound mail while the primary system is unavailable.","d8-email-reliable"),
      C("c8-email-parts","Five parts of email","A complete service combines transport, delivery, client access, list processing and filtering.","The five parts are: MTA for server-to-server transport; MDA for destination storage; access servers using POP3/IMAP4 for MUAs; list processing; and antispam/antivirus filtering.","p. 25",["MTA","MDA","MUA","POP3","IMAP4"],"The MTA receives a message, filtering scans it, the MDA stores it and IMAP exposes it to the client.","d8-email-flow"),
      C("c8-email-security","Email security and communication","Email servers are targets and email is a conduit for malware and leakage; prevent open relays and interception, support encryption and communicate policy.","Security issues include server vulnerabilities, malware and confidential-data leakage, open relays and interception. Other services include encryption and retention policy; all users must understand associated policies.","pp. 26-27",["open relay","malware","data leakage","encryption"],"The service blocks unauthorised relay and scans attachments before delivery.","d8-email-security"),
      C("c8-print-central","Print centralisation trade-offs","More printers improve convenience and variety but increase cost; shared central printers can fund higher-quality equipment.","A typical office has a shared printer per area. More printers mean convenience but cost more. A centralized shared printer can be sufficiently cheaper to purchase a higher-quality device.","p. 28",["shared printer","centralisation","cost centre"],"One high-capacity duplex printer replaces several unreliable desktop devices.","d8-print"),
      C("c8-print-policy","Print architecture policy","Written policy defines sharing ratio, personal-printer eligibility, networking, supply ownership, long-term standards and current recommended models.","Policy indicates how many people share a printer, who qualifies for personal printers, networking, supplies and equipment standards. Standards separate long-term requirements from current recommended printers and configurations.","p. 29",["print policy","duplex","equipment standard","supplies"],"The standard requires network printing and duplex capability, while an appendix lists current models.","d8-print-policy"),
      C("c8-print-docs","Print documentation and environment","Customers need a HOWTO, printer list and labels; printing should minimise paper and toner waste and recycle cartridges.","SAs provide a print HOWTO, list of printers and labels. Print systems should minimize waste; a page not printed has lower impact than one printed and recycled, and toner cartridges should be recycled.","pp. 30-31",["print HOWTO","printer label","toner","waste"],"Default duplex and clear printer location labels reduce waste and support calls.","d8-print-docs")
    ]),
    M("ch8-m4",8,"Storage, backup & recovery","STORE + RECOVER",62,[
      C("c8-storage-terms","Disk and RAID terminology","Storage includes spindles or solid-state media, controllers and host adapters; RAID combines drives for greater capacity, reliability or speed.","Key components are spindle, platters, head, solid-state disk, drive controller and host bus adapter. RAID uses multiple independent drives to provide storage larger, more reliable or faster than one drive.","p. 32",["SSD","drive controller","HBA","RAID level"],"A RAID set continues service after a supported drive failure.","d8-storage"),
      C("c8-storage-types","Volumes, filesystems, DAS, NAS and SAN","A server sees storage as volumes formatted with filesystems; access architecture may be directly attached, network attached or a storage-area network.","A volume is a chunk of storage as seen by the server and is formatted with a file system. Storage types include DAS, NAS and SAN.","p. 33",["volume","file system","DAS","NAS","SAN"],"A shared NAS exposes file storage while a SAN presents block volumes to servers.","d8-storage-types"),
      C("c8-manage-storage","Managing storage","Treat storage as a shared service: assess needs, map groups to infrastructure, maintain inventory/spares, plan growth and establish standards.","Managing storage includes reframing it as a community resource, needs assessment, mapping groups, inventory and spares policy, future planning and standards.","p. 34",["needs assessment","inventory","spares policy","storage standard"],"Departments receive tiers based on measured performance, retention and capacity needs.","d8-storage-manage"),
      C("c8-storage-service","Storage SLA and backup","Storage SLAs cover availability and response; RAID or NAS can improve reliability, but RAID is not itself a backup.","Storage service concerns include SLAs for availability and response time, reliability, and backups. RAID is not a backup strategy, though mirrors can support backup workflows.","p. 35",["storage SLA","availability","response time","RAID mirror"],"An accidental deletion must be restored from backup even though every RAID disk is healthy.","d8-storage-sla"),
      C("c8-evaluate","Storage performance and CDP","Evaluate drive speed, fragmentation, widening access-density limits and continuous data protection of changes to secondary storage.","Disk access density is the widening gap between storage capacity and how quickly data moves. Continuous data protection copies changes within a specified time window to secondary locations.","p. 36",["disk access density","fragmentation","CDP","secondary storage"],"CDP preserves recent changes between scheduled full backups.","d8-cdp"),
      C("c8-storage-problems","Common storage bottlenecks","Real performance depends on sustained—not burst—speed and may bottleneck at disks, chassis bus, backplane, controller/HBA, cache memory or network.","Common problems include large physical infrastructure, timeouts and saturation. Limits include sustained drive I/O, chassis bus, shared backplane, controller/HBA, cache memory and network speed.","p. 37",["sustained I/O","saturation","backplane","timeout"],"A fast drive array still performs poorly when the shared controller is saturated.","d8-storage-problem"),
      C("c8-restore-reasons","Reasons to restore","Restore operations recover accidental deletion, rebuild after disk failure or retrieve an archival snapshot for disaster, legal or fiduciary needs.","Reasons are accidental file deletion, disk failure requiring all data, and archival snapshots for disaster recovery, legal or fiduciary reasons.","p. 38",["file restore","disk failure","archival","disaster recovery"],"Legal staff request a dated snapshot while an employee requests one deleted document.","d8-restore"),
      C("c8-recovery-policy","Recovery policy, SLA and schedule","A company-wide guideline defines why and what to back up, recovery SLA, backup schedule, backup/restore speed and time/capacity planning.","The guideline defines why backups are required, what constitutes a backup and what data is protected. It includes a recovery SLA and policy, schedule, time and capacity planning, backup speed, restore speed and HA databases.","p. 39",["recovery SLA","backup schedule","backup speed","restore speed"],"A four-hour recovery promise is tested against actual restore throughput and data volume.","d8-recovery"),
      C("c8-media","Backup media inventory and off-site storage","Fast reliable recovery depends on accurate media inventory, good media quality and safe off-site storage.","The ability to restore depends on inventory quality; better inventory enables quicker restore. Backup media must be stored safely, and off-site storage is better.","p. 40",["tape inventory","backup media","off-site storage"],"The catalogue identifies the exact off-site tape needed for a dated restore.","d8-media"),
      C("c8-backup-central","Centralised backup","Backups should be centralised because they are important and expensive, allowing investments and costs to be spread across many systems.","Backups should be centralized because they are expensive and important. The investment in backup and restore can be spread over many systems, reducing major costs.","p. 41",["centralized backup","shared cost","restore service"],"One protected platform serves many application teams instead of duplicate tape systems.","d8-backup-central")
    ]),
    M("ch8-m5",8,"Repositories & web services","DISTRIBUTE + SCALE + SECURE",58,[
      C("c8-repository","Repository types","A software repository stores installable packages; it may distribute releases or operating systems, mirror a vendor, or delay packages through a controlled mirror.","Repository types are software release distribution, OS repository, exact vendor mirror, and controlled mirror that delays local access after vendor release.","pp. 42-43",["software repository","OS repository","vendor mirror","controlled mirror"],"A controlled mirror holds a new update until local testing finishes.","d8-repo"),
      C("c8-repo-manage","Repository governance","Document access, package addition and promotion, authentication, supported OSs, bug reporting, requests, licence compliance and source archival.","Decide who has access, adds packages and promotes stages; how identity is authenticated; suitable OSs; bug and package-request paths; licence management and compliance; and source-code archiving.","p. 44",["package promotion","license compliance","source archive","authentication"],"Only release engineers promote a signed package from test to production.","d8-repo-manage"),
      C("c8-web-types","Four basic web server types","Web services may serve static documents, generate CGI pages, build pages from databases or deliver multimedia.","The four types are static web servers, CGI servers, database-driven websites and multimedia servers.","p. 45",["static server","CGI","database-driven","multimedia server"],"A documentation site is static while an inventory portal builds pages from database records.","d8-web-types"),
      C("c8-scaling","Horizontal and vertical scaling","Horizontal scaling replicates equivalent resources and divides load; vertical scaling separates a request into specialised service layers.","Horizontal scaling replicates web resources and divides load, such as two identical web servers. Vertical scaling separates the kinds of subservices used to create a page.","pp. 46-48",["horizontal scaling","vertical scaling","load balancer","shared database"],"A load balancer spreads requests across web replicas, which call a separate database tier.","d8-web-scale"),
      C("c8-web-security","Web security and reliability","Internal web systems still face malware, privileged-data, visitor and network-compromise risks; security fixes also prevent accidental denial of service and improve reliability.","Practice internal web security because malware moves internally, intranets hold privileged data, visitors may have network access and networks may be compromised. Security and reliability go hand-in-hand.","p. 49",["intranet","authentication","denial of service","security patch"],"Authentication and current patches protect HR information and reduce outage risk.","d8-web-security"),
      C("c8-cms","Web content management","A CMS enables self-service content while policy distinguishes routine updates, structural changes and corrections or fixes.","A CMS empowers users to perform self-service updates. Policy should distinguish update (newer material), change (site structure) and fix (content or behaviour that fails standards).","p. 50",["CMS","update","change","fix"],"A typo uses the fix path; a new directory follows the more controlled change path.","d8-cms")
    ])
  ]}
];

export const allModules = chapters.flatMap((c) => c.modules);
export const allConcepts = allModules.flatMap((m) => m.concepts);
export const glossary = allConcepts
  .flatMap((c) =>
    c.terms.map((term) => ({
      term,
      concept: c.title,
      definition: glossaryDefinition(term, c.simple),
      conceptId: c.id,
      sourcePage: c.sourcePage,
    })),
  )
  .sort((a, b) => a.term.localeCompare(b.term));
